setwd("/scratch/mentors/nkong/smanchan/Code/clustspec/")
library(devtools)
library(roxygen2)
document()
install(".")
library(clustspec)
library(lattice)
samea <- persondf("Samea", 1:2, data.frame(1:50, 50:1), data.frame(1:50, 50:1))
otra <- persondf("Sameer", 1:2, data.frame(1:51, 51:1), data.frame(1:51, 51:1))
m <- matrix(runif(500), nrow=10)
pc <- getPrComps(m)
km <- kmeansCH(pc)
x <- forestSelect(m, km$cluster, 7)
