setwd("~/Research/clustspec")
document()
install(".")
library(clustspec)
library(lattice)
persondf.plot(samea)
reduceAndConcat(samea)
otra <- persondf("Sameer", 1:2, data.frame(1:51, 51:1), data.frame(1:51, 51:1))
mmbd <- minMaxByDay(samea, otra)
reduceAndConcat(samea, otra)
