setwd("~/Downloads/clustspec")
library(devtools)
document()
install(".")
library(clustspec)
library(lattice)
samea <- persondf("Samea", 1:2, data.frame(1:50, 50:1), data.frame(1:50, 50:1))
otra <- persondf("Sameer", 1:2, data.frame(1:51, 51:1), data.frame(1:51, 51:1))
m <- matrix(runif(500), nrow=10)
pc <- getPrComps(m)
kmeansPCA(m)
